### ISSUE TITLE
add jmap-client-ts lib on jmap.io

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/jmap-client-ts#27]
#### CURRENT

No referenced 

#### TO DO

https://jmap.io/software.html

`If you’re working on a project that uses JMAP, please [open an issue](https://github.com/jmapio/jmap/issues) or make a [pull request](https://github.com/jmapio/jmap/pulls) on GitHub to update this page.`

Also reference ` jmap-client-ts lib` to https://github.com/linagora/jmap-client

**Comment by alagane** [comment]
Related pull requests:
* Add to jmap.io https://github.com/jmapio/jmap/pull/352
* Reference on jmap-client https://github.com/linagora/jmap-client/pull/88
