### ISSUE TITLE
Create Gitter

### ISSUE THREAD

**Issue by alagane** [OpenPaaS-Suite/jmap-client-ts#29]
To have a way to have direct discussions with the community

**Comment by jeserkin** [comment]
https://gitter.im/linagora/jmap-client

**Comment by alagane** [comment]
> https://gitter.im/linagora/jmap-client

This gitter should not be used anymore since it is about a "jmap-client" project not maintained anymore.

Also I am closing the issue because we finally chose to use issues instead of gitter (and issues discussions are easily traceable and we can create new issues if we are out of scope).

**Comment by jeserkin** [comment]
Having online chat is useful as well, but that would require wider use of this product.
