### ISSUE TITLE
Setup linter

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/jmap-client-ts#3]
Setup a linter to ensure a consistent code style.

**Comment by alagane** [comment]
Husky https://github.com/typicode/husky could also be added to ensure formatting is ok before committing/pushing.

**Comment by oubchid** [comment]
We could also use ESLint rather than TSLint 
https://github.com/Microsoft/TypeScript/issues/29288#developer-productivity-tools-and-integration

**Comment by alagane** [comment]
Related merge request: https://github.com/OpenPaaS-Suite/jmap-client-ts/pull/13
