### ISSUE TITLE
Support Email/changes

### ISSUE THREAD

**Issue by alagane** [OpenPaaS-Suite/jmap-client-ts#32]
https://jmap.io/spec-mail.html#emailchanges

**Comment by alagane** [comment]
Related pull request: https://github.com/OpenPaaS-Suite/jmap-client-ts/pull/37

**Comment by alagane** [comment]
I think I mistook Email and Mailbox changes issues. I renamed them, the correct name for this one is Support Email/changes

**Comment by jeserkin** [comment]
If possible, it would be nice to see some usage example. I did look in documentation, but it shows on abstract objects aka Foo, etc. Would be nice to see code example where this can be applied on email level.

**Comment by alagane** [comment]
> If possible, it would be nice to see some usage example. I did look in documentation, but it shows on abstract objects aka Foo, etc. Would be nice to see code example where this can be applied on email level.

Do you mean some JMAP examples? Then you can look at James integration tests https://github.com/linagora/james-project/blob/master/server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailChangesMethodContract.scala

**Comment by jeserkin** [comment]
> Do you mean some JMAP examples? Then you can look at James integration tests https://github.com/linagora/james-project/blob/master/server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailChangesMethodContract.scala

I was thinking more of a JSON example. What is being sent in request and what is coming back in response.
