### ISSUE TITLE
Suggestion to use Axios instead of pure XMLHttpRequest

### ISSUE THREAD

**Issue by jeserkin** [OpenPaaS-Suite/jmap-client-ts#4]
I was looking through code and one thing that stuck in my eye more than anything else was, that `http-request.ts` was using pure XMLHttpRequest.

If the idea is to not add any new dependencies, then I'd suggest using https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

But if dependencies are not the issue, then https://github.com/axios/axios is a good fit.

**Comment by oubchid** [comment]
@jeserkin  
Yes right, we can use axios it represents only 4.6 kB (MINIFIED + GZIPPED) and is more secure

**Comment by alagane** [comment]
Related pull request: https://github.com/OpenPaaS-Suite/jmap-client-ts/pull/28

**Comment by jeserkin** [comment]
One thing to note. I see, that Axios is under `devDependencies` in **package.json**. This isn't correct. There is a Transport implementation for it and it is not intended purely for tests. In that case it should be under `dependencies` section.

**Comment by alagane** [comment]
> One thing to note. I see, that **Axios** is under `devDependencies` in **package.json**. This isn't correct. There is a Transport implementation for it and it is not intended purely for tests. In that case it should be under `dependencies` section.

Thank you for the remark.
I am looking for a way to choose the implementation for transport, and provide the dependencies needed on runtime. I will take a look at optional dependencies (with NPM), I think there is a mechanism for this.

Also I am open to any suggestions on how to resolve this issue.

**Comment by alagane** [comment]
On jmap-draft-client, these dependencies (request, jquery) are devDependencies (see [package.json](https://ci.linagora.com/linagora/lgs/openpaas/jmap-draft-client/blob/master/package.json)

jquery implementation: https://ci.linagora.com/linagora/lgs/openpaas/jmap-draft-client/blob/master/lib/transport/JQueryTransport.js
request implementation: https://ci.linagora.com/linagora/lgs/openpaas/jmap-draft-client/blob/master/lib/transport/RequestTransport.js

The difference is, with jmap-client-ts we provide them in the constructor. In jmap-client-draft we assume it is global (jquery) or installed as dependency (request).

**Comment by jeserkin** [comment]
> Also I am open to any suggestions on how to resolve this issue.

I don't think I have access to those links. But...

Basically how I approach library, that is not intended purely for development (e.g. Jest). I create MVP app and add **jmap-client-ts** to `devDependencies` in package.json of that app. The I build app and serve it from local server and I will see if it will work or not.

Dependencies, that are provided under `dependencies` section of package.json are available also after build.

**Comment by alagane** [comment]
> Dependencies, that are provided under `dependencies` section of package.json are available also after build.

And that is the problem.
We have multiple implementations of Transport available on jmap-client-ts.

Two cases
**We put axios (and node-fetch, and other dependencies needed by Transport implementations) in dependencies**
If the library user want to use the fetch implementation, they would also need to have in their project axios and other dependencies needed by Transport implementations; even if they don't need them.
* `+` Easier to setup, no need to provide and manage dependency at user level
* `-` Might import not needed dependencies because jmap-client-ts has them as dependencies

**We put acxios (and others...) in devDependencies**
The library user want to use the fetch implementation, they just has to provide the dependency they want (needed by the transport implementation they choose) so that other not needed dependencies are not included
* `+` Not needed to include unused dependencies
* `-` Have to manage the dependency at user level, harder to set up

**Comment by alagane** [comment]
> On jmap-draft-client, these dependencies (request, jquery) are devDependencies (see [package.json](https://github.com/linagora/jmap-draft-client/blob/master/package.json))
> 
> jquery implementation: https://github.com/linagora/jmap-draft-client/blob/master/lib/transport/JQueryTransport.js
> request implementation: https://github.com/linagora/jmap-draft-client/blob/master/lib/transport/RequestTransport.js

Updated the links (now using the GitHub repository)

**Comment by jeserkin** [comment]
I can't speak for everybody, but in my experience most real world application these days are created with Angular/React and those framework/libraries provide own transport mechanisms. In Angular it is [HttpClient](https://angular.io/api/common/http/HttpClient).
Why is this relevant? To simply put it, due to those mechanisms it is more beneficial  to create own transport implementation, rather than use default on, that is also requiring additional dependency.
How I would personally resolve it, is by making a note about it in README.md. It could be something as simple as saying, that following transport implementations would require additional dependency
If developer decides to use one of the existing Transport implementations, he can easily add it by using instruction in README file.

But that is just a suggestion on my part.
