### ISSUE TITLE
Is example for Email/query accurate?

### ISSUE THREAD

**Issue by jeserkin** [OpenPaaS-Suite/jmap-client-ts#48]
I was looking through the code and found my old comment in `Email/query`. At the moment sorting is resolved through 
```
comparator: [{
  property: 'receivedAt',
  isAscending: false
}]
```
even though there is no such property in any documentation (don't remember where it was found).

On the other hand first example on this page https://jmap.io/spec-mail.html#examples shows something different. It shows, that there should be `sort` property. It is present in documentation, but it is not working.

So the question is, is documentation correct regarding this or it needs to be updated to reflect the actual state?

**Comment by chibenwa** [comment]
s/comparator/sort => https://github.com/apache/james-project/pull/361 yes

**Comment by alagane** [comment]
This was a James issue, **not related to jmap-client-ts** I guess, closing the issue, reopen with a comment if needed.

**Comment by chibenwa** [comment]
Don't we need to adapt the jmap-client-ts data model as well?

**Comment by alagane** [comment]
> Don't we need to adapt the jmap-client-ts data model as well?

https://github.com/OpenPaaS-Suite/jmap-client-ts/blob/76366b571dd8df6af458715ca8e415d659948f81/src/types.ts#L103

I think we don't :)

**Comment by jeserkin** [comment]
Mhm. It is present, it is just not used by James at the moment, but since PR is up and we can expect it to become viable soon, then this issue can stay closed.
It would be nice if uses here would have labels though.
e.g. `Feature`, `Bug`, `Question`.

This one is def. a `Question`

**Comment by chibenwa** [comment]
![Screenshot from 2021-04-06 22-29-44](https://user-images.githubusercontent.com/6928740/113736779-9c7eb380-9727-11eb-9d60-1c530f60a310.png)

There's already labels. You don't succeed to add them here?
