### ISSUE TITLE
Have tests

### ISSUE THREAD

**Issue by chibenwa** [OpenPaaS-Suite/jmap-client-ts#6]
No tests sounds like a **bad idea***:

I would suggest to use linagora/james-memorydocker image to start a JMAP server against which to test the cient...

**Comment by jeserkin** [comment]
In general I support presence of tests, but there should be a distinction between unit tests and E2E tests. From my understanding you are talking about the latter.

**Comment by Arsnael** [comment]
Should at least have unit tests. Meanwhile we can discuss if we should have or not tests towards some simulated backend like James memory but I think we can agree that no tests at all is not good

**Comment by jeserkin** [comment]
My suggestion for unit tests would be https://jestjs.io/. It is lightweight, provides enough functionality for unit testing and has a huge community

**Comment by chibenwa** [comment]
> From my understanding you are talking about the latter.

Yes, you are right.

From my experience, they are more expensive to write/run but they enable easier refactorings as they make little assumptions about the tested code and its APIs (no mock)

On apache/james a memory integration test suite with 600+ tests takes about 3 minute to run, I believe this would be a good addition to this project.

**Comment by alagane** [comment]
I started using Mocha, but for parts of the app that are not used yet.

Making E2E tests seems very useful for this project yes.

**Comment by jeserkin** [comment]
@alagane I strongly recommend to consider Jest.

**Comment by alagane** [comment]
Closed by #16 & #17

**Comment by jeserkin** [comment]
I don't think this issue should be closed. For now I have found only integration tests. I don't think I can run them locally, since they don't contain any mocks.
Therefore IMO there also should be unit tests, beside integrations tests.
